from OpenAiMessage import OpenAiMessage
from dataclasses import dataclass

@dataclass
class OpenAiResponse:
    """OpenAI API response model.

    Attributes:
        id (str): The unique identifier for the response.
        object (str): The type of object returned.
        created (int): The timestamp when the response was created.
        model (str): The name of the model used to generate the response.
        choices (list): A list of choices generated by the model.
        usage (dict): Information about token usage in the request and response.
    """

    id: str
    object: str
    created: int
    model: str
    choices: list[OpenAiMessage]
    usage: dict